packages:
  - "packages/*"
  - "apps/*"
  - "docs"
allowBuilds:
  '@swc/core': true
  core-js: true
  esbuild: true
minimumReleaseAgeExclude:
  - '@turbo/darwin-64@2.10.5'
  - '@turbo/darwin-arm64@2.10.5'
  - '@turbo/linux-64@2.10.5'
  - '@turbo/linux-arm64@2.10.5'
  - '@turbo/windows-64@2.10.5'
  - '@turbo/windows-arm64@2.10.5'
  - turbo@2.10.5
