/** `IncidentPayload` -> `incidentPayload`. */
export function lowerCamel(name: string): string {
	return name.charAt(0).toLowerCase() + name.slice(1);
}

/** `IncidentPayload` -> `incidentPayloadSchema`. */
export function schemaConst(name: string): string {
	return `${lowerCamel(name)}Schema`;
}

/**
 * `TypeIncidentValue` -> `typeIncidentValues`, `TimeZones` -> `timeZonesValues`.
 * Trimming the singular suffix keeps the tuple from reading `...ValueValues`.
 */
export function valuesConst(name: string): string {
	const stem = name.endsWith("Value") ? name.slice(0, -"Value".length) : name;
	return `${lowerCamel(stem)}Values`;
}

/** `TypeIncidentValue` -> `typeIncidentValueMeta`. */
export function metaConst(name: string): string {
	return `${lowerCamel(name)}Meta`;
}

/** `TypeAidNonfdValue` -> `type_aid_nonfd.yml`, the value-set file it joins to. */
export function valueSetFileName(name: string): string {
	const stem = name.startsWith("Type") ? name.slice("Type".length) : name;
	const body = stem.endsWith("Value") ? stem.slice(0, -"Value".length) : stem;
	const snake = body
		.replace(/([a-z0-9])([A-Z])/g, "$1_$2")
		.replace(/([A-Z])([A-Z][a-z])/g, "$1_$2")
		.toLowerCase();
	return `type_${snake}.yml`;
}

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

export function propertyKey(key: string): string {
	return IDENTIFIER.test(key) ? key : JSON.stringify(key);
}

export function literal(value: string | number | boolean): string {
	return typeof value === "string" ? JSON.stringify(value) : String(value);
}

export function header(sourceVersion: string): string {
	return [
		"// Generated by packages/neris/scripts/generate.ts. Do not edit.",
		`// Source: NERIS ${sourceVersion}. Regenerate with \`pnpm --filter @pyra/neris generate\`.`,
		"",
	].join("\n");
}
